In [31]:
#importing pandas to work in pandas to clean and analyze this data!
import pandas as pd

In [71]:
#in this notebook, I comb through the discretionary funding set aside by the City Council for FY26.
#Discretionary funding is the money set aside for *local community needs* and programs. 
#When combing through the data, I noticed that nearly $200,000 was set aside for programs that specifically focus on instilling Zionist values in New Yorkers, especially young New Yorkers.
#It's a tiny amount given the total FY26 budget, but I think worth asking what allegience to Israel has to do with local community needs.

In [32]:
#loading the data set
FY26_data = pd.read_csv('../data/NEW-Funded-Disclosure-FY2026.csv', encoding="latin-1")

In [33]:
#taking a look at the first rows of the data set, all the discretionary funding for FY26
FY26_data.head()

,MOCS ID#,Fiscal Year,Source,Council Member,Legal Name,Tax ID,Status,Amount,Agency,Program Name,Grantee Street Address 1,Grantee Street Address 2,City,State,Postal Code,CM Purpose of Funds,Fiscal Conduit,Fiscal Conduit EIN
0,FY26 00001,2026,Local,Restler,84th Precinct Community Council,113149257,Cleared,"$5,000",DYCD,NaN,301 Gold Street,NaN,Brooklyn,NY,11201,To support the operations of the 84th Precinct...,NaN,NaN
1,FY26 00002,2026,Local,Bottcher,"1 World Expo, Inc.",813891758,Cleared,"$5,000",DYCD,NaN,134-47 166th Pl.,Suite 10C,Jamaica,NY,11434,To support civic education and programming in ...,NaN,NaN
2,FY26 00005,2026,Aging,Brooks-Powers,"100 Suits for 100 Men, Inc.",462971279,Cleared,"$7,000",DFTA,Council District 31,227-12A Merrick Blvd,Laurelton NY 11413,Queens,NY,11413,"Funding is to support services to seniors, inc...",NaN,NaN
3,FY26 00006,2026,Community Safety and Victim Services,Brooks-Powers,"100 Suits for 100 Men, Inc.",462971279,Cleared,"$10,000",DYCD,Council District 31,227-12A Merrick Blvd,Laurelton NY 11413,Queens,NY,11413,Funding to support anti-violence and community...,NaN,NaN
4,FY26 00003,2026,Local,Adams,"100 Suits for 100 Men, Inc.",462971279,Cleared,"$10,000",DFTA,NaN,227-12A Merrick Blvd,Laurelton NY 11413,Queens,NY,11413,Funds will provide services for seniors in Roc...,NaN,NaN

In [34]:
#looking at all the columns in the FY26 discretionary funds
FY26_data.columns

Index(['MOCS ID#', 'Fiscal Year', 'Source', 'Council Member', 'Legal Name',
       'Tax ID', 'Status', 'Amount', 'Agency', 'Program Name',
       'Grantee Street Address 1', 'Grantee Street Address 2', 'City', 'State',
       'Postal Code', 'CM Purpose of Funds', 'Fiscal Conduit',
       'Fiscal Conduit EIN'],
      dtype='object')

In [43]:
#I know that the city council sets aside discretionary funds for organizations with the purpose to instill Zionist values in New Yorkers. Creating a data set with just those orgs.

contains_israel = FY26_data[FY26_data["Legal Name"].str.contains("israel", case=False, na=False)]

In [ ]:
#seeing the full list of orgs that might possibly foster support for Israel.
contains_israel

,MOCS ID#,Fiscal Year,Source,Council Member,Legal Name,Tax ID,Status,Amount,Agency,Program Name,Grantee Street Address 1,Grantee Street Address 2,City,State,Postal Code,CM Purpose of Funds,Fiscal Conduit,Fiscal Conduit EIN
183,FY26 05401,2026,Adult Literacy Forward (Formerly Adult Literac...,NaN,"Agudath Israel of America Community Services, ...",133975090,Cleared,"$693,893",DYCD,NaN,42 Broadway,14th floor,NY,NY,10004,To provide support services to students and fu...,NaN,NaN
184,FY26 00074,2026,Aging,Felder,"Agudath Israel of America Community Services, ...",133975090,Cleared,"$5,000",DFTA,Boro Park Senior Center,42 Broadway,14th floor,NY,NY,10004,Funds will be used for printing of newsletters...,NaN,NaN
185,FY26 00075,2026,Aging,Louis,"Agudath Israel of America Community Services, ...",133975090,Cleared,"$5,000",DFTA,Brookdale Neighborhood Center - Council Distri...,42 Broadway,14th floor,NY,NY,10004,Funds will support programming at Brookdale Ne...,NaN,NaN
186,FY26 00076,2026,Aging,Felder,"Agudath Israel of America Community Services, ...",133975090,Cleared,"$25,000",DFTA,Brookdale Senior Center,42 Broadway,14th floor,NY,NY,10004,Funds will be used for printing of newsletters...,NaN,NaN
187,FY26 00077,2026,Aging,Gennaro,"Agudath Israel of America Community Services, ...",133975090,Cleared,"$16,000",DFTA,Council District 24,42 Broadway,14th floor,NY,NY,10004,Funds will be used for social and cultural pro...,NaN,NaN
188,FY26 00079,2026,Aging,De La Rosa,"Agudath Israel of America Community Services, ...",133975090,Cleared,"$10,000",DFTA,Moriah Older Adult Luncheon Club,42 Broadway,14th floor,NY,NY,10004,To support programming at the Moriah Older Adu...,NaN,NaN
189,FY26 00080,2026,Aging,Joseph,"Agudath Israel of America Community Services, ...",133975090,Cleared,"$10,000",DFTA,Older Adult Literacy - Council District 40,42 Broadway,14th floor,NY,NY,10004,Fund to be used for Older Adult Literacy relat...,NaN,NaN
190,FY26 08286,2026,Community Housing Preservation Strategies,NaN,"Agudath Israel of America Community Services, ...",133975090,Cleared,"$102,000",HPD,HPI,42 Broadway,14th floor,NY,NY,10004,This initiative supports organizations that wo...,NaN,NaN
191,FY26 08776,2026,Elie Wiesel Holocaust Survivors,NaN,"Agudath Israel of America Community Services, ...",133975090,Cleared,"$30,000",DFTA,NaN,42 Broadway,14th floor,NY,NY,10004,This initiative will support Holocaust survivo...,NaN,NaN
192,FY26 00073,2026,Local,Vernikov,"Agudath Israel of America Community Services, ...",133975090,Cleared,"$5,000",DYCD,NaN,42 Broadway,14th floor,NY,NY,10004,"Funding to support education, career counselin...",NaN,NaN
193,FY26 00078,2026,Local,Ariola,"Agudath Israel of America Community Services, ...",133975090,Cleared,"$5,000",DYCD,Council District 32,42 Broadway,14th floor,NY,NY,10004,Funds will be used for educational programming...,NaN,NaN
194,FY26 08904,2026,Support Our Older Adults,Felder,"Agudath Israel of America Community Services, ...",133975090,Cleared,"$15,000",DFTA,NaN,42 Broadway,14th floor,NY,NY,10004,This funding will support district-based older...,NaN,NaN
195,FY26 08905,2026,Support Our Older Adults,Gennaro,"Agudath Israel of America Community Services, ...",133975090,Cleared,"$10,000",DFTA,COPE Program,42 Broadway,14th floor,NY,NY,10004,This funding will support district-based older...,NaN,NaN
196,FY26 08906,2026,Support Our Older Adults,De La Rosa,"Agudath Israel of America Community Services, ...",133975090,Cleared,"$10,000",DFTA,Moriah Older Adult Luncheon Club - Council Dis...,42 Broadway,14th floor,NY,NY,10004,This funding will support district-based older...,NaN,NaN
4789,FY26 06850,2026,Cultural Immigrant Initiative,Brewer,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$10,000",DYCD,Israeli-American Youth Movement - Council Dist...,575 8th Avenue,NaN,New York,NY,10018,The funds will be used to support cultural org...,NaN,NaN
4790,FY26 02095,2026,Local,Dinowitz,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$5,000",DYCD,NYC Israeli Scouts - Council District 11,575 8th Avenue,NaN,New York,NY,10018,Funding to support scout programming and commu...,NaN,NaN
4791,FY26 02096,2026,Local,Schulman,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$1,500",DYCD,"Programming, Events & Seminars",575 8th Avenue,NaN,New York,NY,10018,Funding will go towards supporting the Scouts'...,NaN,NaN
4792,FY26 02093,2026,Youth,Powers,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$5,000",DYCD,NaN,575 8th Avenue,NaN,New York,NY,10018,Funding will support the NYC Israeli Scouts we...,NaN,NaN
4793,FY26 02094,2026,Youth,Menin,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$5,000",DYCD,Council District 5,575 8th Avenue,NaN,New York,NY,10018,Funds will be used to support the NYC Israeli ...,NaN,NaN
4794,FY26 02097,2026,Youth,Abreu,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$10,000",DYCD,Youth Programming - Council District 7,575 8th Avenue,NaN,New York,NY,10018,Funding to support community events and youth ...,NaN,NaN
5590,FY26 02502,2026,Aging,Stevens,"Hope of Israel Senior Citizens Center, Inc.",132749857,Cleared,"$10,000",DFTA,Senior Center - Council District 16,1068 Gerard Avenue,NaN,Bronx,NY,10452,Funding to support recreational activities and...,NaN,NaN
5591,FY26 02501,2026,Local,Speaker,"Hope of Israel Senior Citizens Center, Inc.",132749857,Cleared,"$20,000",DFTA,NaN,1068 Gerard Avenue,NaN,Bronx,NY,10452,Funds will be used to purchase supplies and eq...,NaN,NaN
5592,FY26 11556,2026,Support Our Older Adults,Stevens,"Hope of Israel Senior Citizens Center, Inc.",132749857,Cleared,"$10,000",DFTA,Council District 16,1068 Gerard Avenue,NaN,Bronx,NY,10452,This funding will support district-based older...,NaN,NaN
9339,FY26 04240,2026,Aging,Holden,Rabbi Israel Meyer HaKohen Rabbinical Seminary...,111752021,Cleared,"$25,000",DFTA,Middle Village Adult Center Senior,69-10 75th Street,NaN,Middle Village,NY,11379,Funds to be used for operating expenses of pro...,NaN,NaN
9340,FY26 10708,2026,Older Adults Across the Boroughs (formerly Bor...,Queens Delegation,Rabbi Israel Meyer HaKohen Rabbinical Seminary...,111752021,Cleared,"$10,000",DFTA,The Middle Village Adult Center,69-10 75th Street,NaN,Middle Village,NY,11379,This allocation supports older adult services ...,NaN,NaN
9341,FY26 09486,2026,Parks Equity Initiative,Holden,Rabbi Israel Meyer HaKohen Rabbinical Seminary...,111752021,Cleared,"$15,000",DPR,Picnic in the Park - Council District 30,69-10 75th Street,NaN,Middle Village,NY,11379,This allocation provides $5.4 million to suppo...,NaN,NaN
11601,FY26 05269,2026,Youth,Gennaro,Young Israel of Jamaica Estates,112518593,Cleared,"$15,000",DYCD,NaN,83-10 188th St.,NaN,Jamaica Estates,NY,11423,"Funding to support children, teens and collegi...",NaN,NaN
11602,FY26 05270,2026,Youth,Carr,Young Israel of Staten Island,132618386,Cleared,"$15,000",DYCD,NaN,835 Forest Hill Rd.,NaN,Staten Island,NY,10314,Funds will be used to support recreational and...,NaN,NaN
11603,FY26 05271,2026,Aging,Felder,"Young Israel Programs, Inc.",30381957,Cleared,"$6,000",DFTA,Senior Services of Midwood - Council District 44,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,Funds will be used to support district based s...,NaN,NaN
11604,FY26 05272,2026,Aging,Schulman,"Young Israel Programs, Inc.",30381957,Cleared,"$50,000",DFTA,Young Israel of Forest Hills Senior League,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,Funding will be used to support the daily meal...,NaN,NaN
11605,FY26 05273,2026,Aging,Gennaro,"Young Israel Programs, Inc.",30381957,Cleared,"$10,000",DFTA,Young Israel of Queens Valley,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,Funds to support programming including recreat...,NaN,NaN
11606,FY26 09286,2026,Support Our Older Adults,Felder,"Young Israel Programs, Inc.",30381957,Cleared,"$5,000",DFTA,Midwood Senior Center,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN
11607,FY26 09285,2026,Support Our Older Adults,Louis,"Young Israel Programs, Inc.",30381957,Cleared,"$10,000",DFTA,Senior Programming - Council District 45,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN
11608,FY26 09287,2026,Support Our Older Adults,Schulman,"Young Israel Programs, Inc.",30381957,Cleared,"$30,500",DFTA,Young Israel of Forest Hills Senior League,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN
11609,FY26 09288,2026,Support Our Older Adults,Brooks-Powers,"Young Israel Programs, Inc.",30381957,Cleared,"$10,000",DFTA,Young Israel of Wavecrest And Bayswater,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN

In [ ]:
#Did some research, Agudath Israel of America Community Services is focused on supporting Jewish values more broadly and should be removed.
#This method creates a data set of every single row that does not have a string that contains "Agudath Israel" in the "Legal Name" column
contains_israel[~contains_israel["Legal Name"].str.contains("Agudath Israel")]

,MOCS ID#,Fiscal Year,Source,Council Member,Legal Name,Tax ID,Status,Amount,Agency,Program Name,Grantee Street Address 1,Grantee Street Address 2,City,State,Postal Code,CM Purpose of Funds,Fiscal Conduit,Fiscal Conduit EIN
4789,FY26 06850,2026,Cultural Immigrant Initiative,Brewer,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$10,000",DYCD,Israeli-American Youth Movement - Council Dist...,575 8th Avenue,NaN,New York,NY,10018,The funds will be used to support cultural org...,NaN,NaN
4790,FY26 02095,2026,Local,Dinowitz,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$5,000",DYCD,NYC Israeli Scouts - Council District 11,575 8th Avenue,NaN,New York,NY,10018,Funding to support scout programming and commu...,NaN,NaN
4791,FY26 02096,2026,Local,Schulman,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$1,500",DYCD,"Programming, Events & Seminars",575 8th Avenue,NaN,New York,NY,10018,Funding will go towards supporting the Scouts'...,NaN,NaN
4792,FY26 02093,2026,Youth,Powers,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$5,000",DYCD,NaN,575 8th Avenue,NaN,New York,NY,10018,Funding will support the NYC Israeli Scouts we...,NaN,NaN
4793,FY26 02094,2026,Youth,Menin,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$5,000",DYCD,Council District 5,575 8th Avenue,NaN,New York,NY,10018,Funds will be used to support the NYC Israeli ...,NaN,NaN
4794,FY26 02097,2026,Youth,Abreu,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$10,000",DYCD,Youth Programming - Council District 7,575 8th Avenue,NaN,New York,NY,10018,Funding to support community events and youth ...,NaN,NaN
5590,FY26 02502,2026,Aging,Stevens,"Hope of Israel Senior Citizens Center, Inc.",132749857,Cleared,"$10,000",DFTA,Senior Center - Council District 16,1068 Gerard Avenue,NaN,Bronx,NY,10452,Funding to support recreational activities and...,NaN,NaN
5591,FY26 02501,2026,Local,Speaker,"Hope of Israel Senior Citizens Center, Inc.",132749857,Cleared,"$20,000",DFTA,NaN,1068 Gerard Avenue,NaN,Bronx,NY,10452,Funds will be used to purchase supplies and eq...,NaN,NaN
5592,FY26 11556,2026,Support Our Older Adults,Stevens,"Hope of Israel Senior Citizens Center, Inc.",132749857,Cleared,"$10,000",DFTA,Council District 16,1068 Gerard Avenue,NaN,Bronx,NY,10452,This funding will support district-based older...,NaN,NaN
9339,FY26 04240,2026,Aging,Holden,Rabbi Israel Meyer HaKohen Rabbinical Seminary...,111752021,Cleared,"$25,000",DFTA,Middle Village Adult Center Senior,69-10 75th Street,NaN,Middle Village,NY,11379,Funds to be used for operating expenses of pro...,NaN,NaN
9340,FY26 10708,2026,Older Adults Across the Boroughs (formerly Bor...,Queens Delegation,Rabbi Israel Meyer HaKohen Rabbinical Seminary...,111752021,Cleared,"$10,000",DFTA,The Middle Village Adult Center,69-10 75th Street,NaN,Middle Village,NY,11379,This allocation supports older adult services ...,NaN,NaN
9341,FY26 09486,2026,Parks Equity Initiative,Holden,Rabbi Israel Meyer HaKohen Rabbinical Seminary...,111752021,Cleared,"$15,000",DPR,Picnic in the Park - Council District 30,69-10 75th Street,NaN,Middle Village,NY,11379,This allocation provides $5.4 million to suppo...,NaN,NaN
11601,FY26 05269,2026,Youth,Gennaro,Young Israel of Jamaica Estates,112518593,Cleared,"$15,000",DYCD,NaN,83-10 188th St.,NaN,Jamaica Estates,NY,11423,"Funding to support children, teens and collegi...",NaN,NaN
11602,FY26 05270,2026,Youth,Carr,Young Israel of Staten Island,132618386,Cleared,"$15,000",DYCD,NaN,835 Forest Hill Rd.,NaN,Staten Island,NY,10314,Funds will be used to support recreational and...,NaN,NaN
11603,FY26 05271,2026,Aging,Felder,"Young Israel Programs, Inc.",30381957,Cleared,"$6,000",DFTA,Senior Services of Midwood - Council District 44,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,Funds will be used to support district based s...,NaN,NaN
11604,FY26 05272,2026,Aging,Schulman,"Young Israel Programs, Inc.",30381957,Cleared,"$50,000",DFTA,Young Israel of Forest Hills Senior League,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,Funding will be used to support the daily meal...,NaN,NaN
11605,FY26 05273,2026,Aging,Gennaro,"Young Israel Programs, Inc.",30381957,Cleared,"$10,000",DFTA,Young Israel of Queens Valley,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,Funds to support programming including recreat...,NaN,NaN
11606,FY26 09286,2026,Support Our Older Adults,Felder,"Young Israel Programs, Inc.",30381957,Cleared,"$5,000",DFTA,Midwood Senior Center,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN
11607,FY26 09285,2026,Support Our Older Adults,Louis,"Young Israel Programs, Inc.",30381957,Cleared,"$10,000",DFTA,Senior Programming - Council District 45,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN
11608,FY26 09287,2026,Support Our Older Adults,Schulman,"Young Israel Programs, Inc.",30381957,Cleared,"$30,500",DFTA,Young Israel of Forest Hills Senior League,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN
11609,FY26 09288,2026,Support Our Older Adults,Brooks-Powers,"Young Israel Programs, Inc.",30381957,Cleared,"$10,000",DFTA,Young Israel of Wavecrest And Bayswater,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN

In [47]:
#this method creates a new data set with all the rows that do not have "Agudath Israel of America Community Services, Inc." in the "Legal Name" column
israel_list1 = contains_israel[contains_israel["Legal Name"]!="Agudath Israel of America Community Services, Inc."]

In [49]:
#checking my new data set
israel_list1

,MOCS ID#,Fiscal Year,Source,Council Member,Legal Name,Tax ID,Status,Amount,Agency,Program Name,Grantee Street Address 1,Grantee Street Address 2,City,State,Postal Code,CM Purpose of Funds,Fiscal Conduit,Fiscal Conduit EIN
4789,FY26 06850,2026,Cultural Immigrant Initiative,Brewer,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$10,000",DYCD,Israeli-American Youth Movement - Council Dist...,575 8th Avenue,NaN,New York,NY,10018,The funds will be used to support cultural org...,NaN,NaN
4790,FY26 02095,2026,Local,Dinowitz,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$5,000",DYCD,NYC Israeli Scouts - Council District 11,575 8th Avenue,NaN,New York,NY,10018,Funding to support scout programming and commu...,NaN,NaN
4791,FY26 02096,2026,Local,Schulman,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$1,500",DYCD,"Programming, Events & Seminars",575 8th Avenue,NaN,New York,NY,10018,Funding will go towards supporting the Scouts'...,NaN,NaN
4792,FY26 02093,2026,Youth,Powers,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$5,000",DYCD,NaN,575 8th Avenue,NaN,New York,NY,10018,Funding will support the NYC Israeli Scouts we...,NaN,NaN
4793,FY26 02094,2026,Youth,Menin,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$5,000",DYCD,Council District 5,575 8th Avenue,NaN,New York,NY,10018,Funds will be used to support the NYC Israeli ...,NaN,NaN
4794,FY26 02097,2026,Youth,Abreu,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$10,000",DYCD,Youth Programming - Council District 7,575 8th Avenue,NaN,New York,NY,10018,Funding to support community events and youth ...,NaN,NaN
5590,FY26 02502,2026,Aging,Stevens,"Hope of Israel Senior Citizens Center, Inc.",132749857,Cleared,"$10,000",DFTA,Senior Center - Council District 16,1068 Gerard Avenue,NaN,Bronx,NY,10452,Funding to support recreational activities and...,NaN,NaN
5591,FY26 02501,2026,Local,Speaker,"Hope of Israel Senior Citizens Center, Inc.",132749857,Cleared,"$20,000",DFTA,NaN,1068 Gerard Avenue,NaN,Bronx,NY,10452,Funds will be used to purchase supplies and eq...,NaN,NaN
5592,FY26 11556,2026,Support Our Older Adults,Stevens,"Hope of Israel Senior Citizens Center, Inc.",132749857,Cleared,"$10,000",DFTA,Council District 16,1068 Gerard Avenue,NaN,Bronx,NY,10452,This funding will support district-based older...,NaN,NaN
9339,FY26 04240,2026,Aging,Holden,Rabbi Israel Meyer HaKohen Rabbinical Seminary...,111752021,Cleared,"$25,000",DFTA,Middle Village Adult Center Senior,69-10 75th Street,NaN,Middle Village,NY,11379,Funds to be used for operating expenses of pro...,NaN,NaN
9340,FY26 10708,2026,Older Adults Across the Boroughs (formerly Bor...,Queens Delegation,Rabbi Israel Meyer HaKohen Rabbinical Seminary...,111752021,Cleared,"$10,000",DFTA,The Middle Village Adult Center,69-10 75th Street,NaN,Middle Village,NY,11379,This allocation supports older adult services ...,NaN,NaN
9341,FY26 09486,2026,Parks Equity Initiative,Holden,Rabbi Israel Meyer HaKohen Rabbinical Seminary...,111752021,Cleared,"$15,000",DPR,Picnic in the Park - Council District 30,69-10 75th Street,NaN,Middle Village,NY,11379,This allocation provides $5.4 million to suppo...,NaN,NaN
11601,FY26 05269,2026,Youth,Gennaro,Young Israel of Jamaica Estates,112518593,Cleared,"$15,000",DYCD,NaN,83-10 188th St.,NaN,Jamaica Estates,NY,11423,"Funding to support children, teens and collegi...",NaN,NaN
11602,FY26 05270,2026,Youth,Carr,Young Israel of Staten Island,132618386,Cleared,"$15,000",DYCD,NaN,835 Forest Hill Rd.,NaN,Staten Island,NY,10314,Funds will be used to support recreational and...,NaN,NaN
11603,FY26 05271,2026,Aging,Felder,"Young Israel Programs, Inc.",30381957,Cleared,"$6,000",DFTA,Senior Services of Midwood - Council District 44,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,Funds will be used to support district based s...,NaN,NaN
11604,FY26 05272,2026,Aging,Schulman,"Young Israel Programs, Inc.",30381957,Cleared,"$50,000",DFTA,Young Israel of Forest Hills Senior League,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,Funding will be used to support the daily meal...,NaN,NaN
11605,FY26 05273,2026,Aging,Gennaro,"Young Israel Programs, Inc.",30381957,Cleared,"$10,000",DFTA,Young Israel of Queens Valley,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,Funds to support programming including recreat...,NaN,NaN
11606,FY26 09286,2026,Support Our Older Adults,Felder,"Young Israel Programs, Inc.",30381957,Cleared,"$5,000",DFTA,Midwood Senior Center,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN
11607,FY26 09285,2026,Support Our Older Adults,Louis,"Young Israel Programs, Inc.",30381957,Cleared,"$10,000",DFTA,Senior Programming - Council District 45,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN
11608,FY26 09287,2026,Support Our Older Adults,Schulman,"Young Israel Programs, Inc.",30381957,Cleared,"$30,500",DFTA,Young Israel of Forest Hills Senior League,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN
11609,FY26 09288,2026,Support Our Older Adults,Brooks-Powers,"Young Israel Programs, Inc.",30381957,Cleared,"$10,000",DFTA,Young Israel of Wavecrest And Bayswater,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN

In [50]:
#Hope of Israel Senior Citizens Center, Inc. should also be removed. Doing so with the same method I used earlier.
israel_list2 = israel_list1[~israel_list1["Legal Name"].str.contains("Hope of Israel Senior Citizens")]

In [52]:
#checking my new list.
israel_list2

,MOCS ID#,Fiscal Year,Source,Council Member,Legal Name,Tax ID,Status,Amount,Agency,Program Name,Grantee Street Address 1,Grantee Street Address 2,City,State,Postal Code,CM Purpose of Funds,Fiscal Conduit,Fiscal Conduit EIN
4789,FY26 06850,2026,Cultural Immigrant Initiative,Brewer,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$10,000",DYCD,Israeli-American Youth Movement - Council Dist...,575 8th Avenue,NaN,New York,NY,10018,The funds will be used to support cultural org...,NaN,NaN
4790,FY26 02095,2026,Local,Dinowitz,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$5,000",DYCD,NYC Israeli Scouts - Council District 11,575 8th Avenue,NaN,New York,NY,10018,Funding to support scout programming and commu...,NaN,NaN
4791,FY26 02096,2026,Local,Schulman,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$1,500",DYCD,"Programming, Events & Seminars",575 8th Avenue,NaN,New York,NY,10018,Funding will go towards supporting the Scouts'...,NaN,NaN
4792,FY26 02093,2026,Youth,Powers,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$5,000",DYCD,NaN,575 8th Avenue,NaN,New York,NY,10018,Funding will support the NYC Israeli Scouts we...,NaN,NaN
4793,FY26 02094,2026,Youth,Menin,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$5,000",DYCD,Council District 5,575 8th Avenue,NaN,New York,NY,10018,Funds will be used to support the NYC Israeli ...,NaN,NaN
4794,FY26 02097,2026,Youth,Abreu,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$10,000",DYCD,Youth Programming - Council District 7,575 8th Avenue,NaN,New York,NY,10018,Funding to support community events and youth ...,NaN,NaN
9339,FY26 04240,2026,Aging,Holden,Rabbi Israel Meyer HaKohen Rabbinical Seminary...,111752021,Cleared,"$25,000",DFTA,Middle Village Adult Center Senior,69-10 75th Street,NaN,Middle Village,NY,11379,Funds to be used for operating expenses of pro...,NaN,NaN
9340,FY26 10708,2026,Older Adults Across the Boroughs (formerly Bor...,Queens Delegation,Rabbi Israel Meyer HaKohen Rabbinical Seminary...,111752021,Cleared,"$10,000",DFTA,The Middle Village Adult Center,69-10 75th Street,NaN,Middle Village,NY,11379,This allocation supports older adult services ...,NaN,NaN
9341,FY26 09486,2026,Parks Equity Initiative,Holden,Rabbi Israel Meyer HaKohen Rabbinical Seminary...,111752021,Cleared,"$15,000",DPR,Picnic in the Park - Council District 30,69-10 75th Street,NaN,Middle Village,NY,11379,This allocation provides $5.4 million to suppo...,NaN,NaN
11601,FY26 05269,2026,Youth,Gennaro,Young Israel of Jamaica Estates,112518593,Cleared,"$15,000",DYCD,NaN,83-10 188th St.,NaN,Jamaica Estates,NY,11423,"Funding to support children, teens and collegi...",NaN,NaN
11602,FY26 05270,2026,Youth,Carr,Young Israel of Staten Island,132618386,Cleared,"$15,000",DYCD,NaN,835 Forest Hill Rd.,NaN,Staten Island,NY,10314,Funds will be used to support recreational and...,NaN,NaN
11603,FY26 05271,2026,Aging,Felder,"Young Israel Programs, Inc.",30381957,Cleared,"$6,000",DFTA,Senior Services of Midwood - Council District 44,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,Funds will be used to support district based s...,NaN,NaN
11604,FY26 05272,2026,Aging,Schulman,"Young Israel Programs, Inc.",30381957,Cleared,"$50,000",DFTA,Young Israel of Forest Hills Senior League,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,Funding will be used to support the daily meal...,NaN,NaN
11605,FY26 05273,2026,Aging,Gennaro,"Young Israel Programs, Inc.",30381957,Cleared,"$10,000",DFTA,Young Israel of Queens Valley,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,Funds to support programming including recreat...,NaN,NaN
11606,FY26 09286,2026,Support Our Older Adults,Felder,"Young Israel Programs, Inc.",30381957,Cleared,"$5,000",DFTA,Midwood Senior Center,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN
11607,FY26 09285,2026,Support Our Older Adults,Louis,"Young Israel Programs, Inc.",30381957,Cleared,"$10,000",DFTA,Senior Programming - Council District 45,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN
11608,FY26 09287,2026,Support Our Older Adults,Schulman,"Young Israel Programs, Inc.",30381957,Cleared,"$30,500",DFTA,Young Israel of Forest Hills Senior League,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN
11609,FY26 09288,2026,Support Our Older Adults,Brooks-Powers,"Young Israel Programs, Inc.",30381957,Cleared,"$10,000",DFTA,Young Israel of Wavecrest And Bayswater,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN

In [53]:
#Rabbi Israel Meyer HaKohen Rabbinical Seminary should also be removed. Doing so with the same method I used earlier.
israel_list3 = israel_list2[~israel_list2["Legal Name"].str.contains("Rabbi Israel Meyer")]

In [58]:
#Checking my final list
israel_list3

,MOCS ID#,Fiscal Year,Source,Council Member,Legal Name,Tax ID,Status,Amount,Agency,Program Name,Grantee Street Address 1,Grantee Street Address 2,City,State,Postal Code,CM Purpose of Funds,Fiscal Conduit,Fiscal Conduit EIN
4789,FY26 06850,2026,Cultural Immigrant Initiative,Brewer,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$10,000",DYCD,Israeli-American Youth Movement - Council Dist...,575 8th Avenue,NaN,New York,NY,10018,The funds will be used to support cultural org...,NaN,NaN
4790,FY26 02095,2026,Local,Dinowitz,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$5,000",DYCD,NYC Israeli Scouts - Council District 11,575 8th Avenue,NaN,New York,NY,10018,Funding to support scout programming and commu...,NaN,NaN
4791,FY26 02096,2026,Local,Schulman,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$1,500",DYCD,"Programming, Events & Seminars",575 8th Avenue,NaN,New York,NY,10018,Funding will go towards supporting the Scouts'...,NaN,NaN
4792,FY26 02093,2026,Youth,Powers,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$5,000",DYCD,NaN,575 8th Avenue,NaN,New York,NY,10018,Funding will support the NYC Israeli Scouts we...,NaN,NaN
4793,FY26 02094,2026,Youth,Menin,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$5,000",DYCD,Council District 5,575 8th Avenue,NaN,New York,NY,10018,Funds will be used to support the NYC Israeli ...,NaN,NaN
4794,FY26 02097,2026,Youth,Abreu,"Friends of Israel Scouts, Inc.",133843506,Cleared,"$10,000",DYCD,Youth Programming - Council District 7,575 8th Avenue,NaN,New York,NY,10018,Funding to support community events and youth ...,NaN,NaN
11601,FY26 05269,2026,Youth,Gennaro,Young Israel of Jamaica Estates,112518593,Cleared,"$15,000",DYCD,NaN,83-10 188th St.,NaN,Jamaica Estates,NY,11423,"Funding to support children, teens and collegi...",NaN,NaN
11602,FY26 05270,2026,Youth,Carr,Young Israel of Staten Island,132618386,Cleared,"$15,000",DYCD,NaN,835 Forest Hill Rd.,NaN,Staten Island,NY,10314,Funds will be used to support recreational and...,NaN,NaN
11603,FY26 05271,2026,Aging,Felder,"Young Israel Programs, Inc.",30381957,Cleared,"$6,000",DFTA,Senior Services of Midwood - Council District 44,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,Funds will be used to support district based s...,NaN,NaN
11604,FY26 05272,2026,Aging,Schulman,"Young Israel Programs, Inc.",30381957,Cleared,"$50,000",DFTA,Young Israel of Forest Hills Senior League,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,Funding will be used to support the daily meal...,NaN,NaN
11605,FY26 05273,2026,Aging,Gennaro,"Young Israel Programs, Inc.",30381957,Cleared,"$10,000",DFTA,Young Israel of Queens Valley,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,Funds to support programming including recreat...,NaN,NaN
11606,FY26 09286,2026,Support Our Older Adults,Felder,"Young Israel Programs, Inc.",30381957,Cleared,"$5,000",DFTA,Midwood Senior Center,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN
11607,FY26 09285,2026,Support Our Older Adults,Louis,"Young Israel Programs, Inc.",30381957,Cleared,"$10,000",DFTA,Senior Programming - Council District 45,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN
11608,FY26 09287,2026,Support Our Older Adults,Schulman,"Young Israel Programs, Inc.",30381957,Cleared,"$30,500",DFTA,Young Israel of Forest Hills Senior League,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN
11609,FY26 09288,2026,Support Our Older Adults,Brooks-Powers,"Young Israel Programs, Inc.",30381957,Cleared,"$10,000",DFTA,Young Israel of Wavecrest And Bayswater,Young Israel Programs,50 Eisenhower Drive,Paramus,NJ,07652,This funding will support district-based older...,NaN,NaN

In [66]:
#checking the data types in the data
israel_list3.dtypes

MOCS ID#                     object
Fiscal Year                   int64
Source                       object
Council Member               object
Legal Name                   object
Tax ID                        int64
Status                       object
Amount                       object
Agency                       object
Program Name                 object
Grantee Street Address 1     object
Grantee Street Address 2     object
City                         object
State                        object
Postal Code                  object
CM Purpose of Funds          object
Fiscal Conduit              float64
Fiscal Conduit EIN          float64
dtype: object

In [68]:
israel_list3.to_csv('israel_funds.csv')